### ISSUE TITLE
Following "Run with Node.js" instructions instead tries to run with PhantomJS

### ISSUE THREAD

**Issue by chronodm** [scala-js/scalajs-tutorial#10]
Steps to reproduce:

- on a system with Node installed (e.g., MacOS with Homebrew Node in `/usr/local/bin`) but not PhantomJS:
- clone the tutorial app
- following the [instructions](http://www.scala-js.org/tutorial/basic/), add `scalaJSUseRhino in Global := false` to the end of the `build.sbt`
- from the console, invoke `sbt run`

Expected:

- tutorial app runs

Actual:

- `java.io.IOException: Cannot run program "phantomjs": error=2, No such file or directory`

```
$ sbt run
[info] Loading project definition from /Users/david/Projects/conditrix-scalajs/project
[info] Set current project to Conditrix (in build file:/Users/david/Projects/conditrix-scalajs/)
[info] Running tutorial.webapp.TutorialApp
java.io.IOException: Cannot run program "phantomjs": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:126)
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:156)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:126)
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:156)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) java.io.IOException: Cannot run program "phantomjs": error=2, No such file or directory
[error] Total time: 2 s, completed Apr 19, 2016 5:01:09 PM
```

**Comment by sjrd** [comment]
That is expected, if you use the HEAD of master. Later in the tutorial, there are other configurations that make it switch to PhantomJS.

Checkout an earlier commit, appropriate for the step of the tutorial you're reading.

**Comment by chronodm** [comment]
This is an issue with the tutorial. The explanation in the tutorial of what triggers the switch from Node to Phantom is unclear. This sentence --

> If you disabled Rhino, this will switch to running your code with PhantomJS instead of Node.js, which you need to install.

-- is presumably meant to imply that you need to install PhantomJS, but on the surface, it suggests you need to install Node.

It would also be helpful, in the "Run with Node.js" section, to add additional text here --

> ```
> scalaJSUseRhino in Global := false
> ```
> This will enable Node.js by default when launching sbt.

-- to clarify that this setting doesn't enable Node, per se, but rather (as its name implies) disables Rhino, causing the runtime to *either* look for Node or for PhantomJS, depending on whether the code requires a DOM.

**Comment by chronodm** [comment]
P.S. It's only "expected" if you already understand ScalaJS. ;)

**Comment by sjrd** [comment]
OK but so you agree that this repository is not faulty? If something should change, it should be the text of the tutorial (in the scala-js-website repo), right?

**Comment by dmolesUC3** [comment]
Agreed!

**Comment by dmolesUC3** [comment]
Sorry to file the issue against the wrong repo.
