### ISSUE TITLE
Run is failed: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by atapin** [scala-js/scalajs-tutorial#12]
I've just checked out the repo and run `sbt run`; getting the following log:

```
> run
[info] Compiling 1 Scala source to /Users/aatapin/opensource/scalajs-tutorial/target/scala-2.12/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.12.1. Compiling...
[info] Resolving org.scala-sbt#interface;0.13.13 ...
[trace] Stack trace suppressed: run last compile:compileIncremental for the full output.
[error] (compile:compileIncremental) java.lang.reflect.InvocationTargetException
[error] Total time: 2 s, completed Jan 12, 2017 1:53:30 PM
> last compile:compileIncremental
[debug] [naha]
[debug] [naha] Initial source changes:
[debug] [naha] 	removed:Set()
[debug] [naha] 	added: Set(/Users/aatapin/opensource/scalajs-tutorial/src/main/scala/tutorial/webapp/TutorialApp.scala)
[debug] [naha] 	modified: Set()
[debug] [naha] Invalidated products: Set()
[debug] [naha] External API changes: API Changes: Set()
[debug] [naha] Modified binary dependencies: Set()
[debug] [naha] Initial directly invalidated sources: Set(/Users/aatapin/opensource/scalajs-tutorial/src/main/scala/tutorial/webapp/TutorialApp.scala)
[debug] [naha]
[debug] [naha] Sources indirectly invalidated by:
[debug] [naha] 	product: Set()
[debug] [naha] 	binary dep: Set()
[debug] [naha] 	external source: Set()
[debug] All initially invalidated sources: Set(/Users/aatapin/opensource/scalajs-tutorial/src/main/scala/tutorial/webapp/TutorialApp.scala)
[debug] [naha] Initial set of included nodes: Set(/Users/aatapin/opensource/scalajs-tutorial/src/main/scala/tutorial/webapp/TutorialApp.scala)
[debug] [naha] Recompiling all 1 sources: invalidated sources (1) exceeded 50.0% of all sources
[info] Compiling 1 Scala source to /Users/aatapin/opensource/scalajs-tutorial/target/scala-2.12/classes...
[debug] Getting org.scala-sbt:compiler-interface:0.13.13:component from component compiler for Scala 2.12.1
[info] 'compiler-interface' not yet compiled for Scala 2.12.1. Compiling...
[debug] Plain interface to Scala compiler 2.12.1  with arguments:
[debug] 	-nowarn
[debug] 	-d
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_7f8d460f
[debug] 	-bootclasspath
[debug] 	/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/classes:/Users/aatapin/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.1.jar
[debug] 	-classpath
[debug] 	/Users/aatapin/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.13/xsbti/interface-0.13.13.jar:/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_e2cda132/srcs/org.scala-sbt/compiler-interface/compiler-interface-0.13.13-sources.jar:/Users/aatapin/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.1.jar:/Users/aatapin/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.1.jar:/Users/aatapin/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar:/Users/aatapin/.ivy2/cache/jline/jline/jars/jline-2.14.1.jar
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/API.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/Analyzer.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/Command.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/Compat.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/CompilerInterface.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/ConsoleInterface.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/DelegatingReporter.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/Dependency.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/ExtractAPI.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/ExtractUsedNames.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/GlobalHelpers.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/LocateClassFile.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/Log.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/Message.scala
[debug] 	/var/folders/y6/mqjjc93s679_x6dj76vrymzc0000gn/T/sbt_606d9a40/xsbt/ScaladocInterface.scala
[info] Resolving org.scala-sbt#compiler-interface;0.13.13 ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.13 ...
java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2ab6 0057 04a0 001e b200 afb2 00b4 04bd
    0000010: 0002 5903 2a53 c000 b6b6 00ba b600 bec0
    0000020: 00c0 b02a b600 31b8 003b 3c1b 04a4 015e
    0000030: 1b05 6c3d 2a1b 056c 2ab6 0031 b700 c23e
    0000040: 2ab6 0031 021d 787e 3604 2ab6 0031 0210
    0000050: 201d 647c 7e36 05bb 0014 59b2 00b4 2ab6
    0000060: 0033 c000 b6b6 00c6 b700 c91c b600 cd3a
    0000070: 0619 06c6 001a 1906 b600 d1c0 007d 3a07
    0000080: 1906 b600 d4c0 007d 3a08 a700 0dbb 00d6
    0000090: 5919 06b7 00d9 bf19 073a 0919 083a 0abb
    00000a0: 0002 5915 0419 09bb 0014 59b2 00b4 1909
    00000b0: c000 b6b6 00c6 b700 c903 b800 df3a 0e3a
    00000c0: 0d03 190d b900 e301 0019 0e3a 1136 1036
    00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    00000e0: 150f b900 e602 00c0 0005 3a17 1911 1917
    00000f0: b800 ea3a 1136 1036 0fa7 ffd8 1911 b800
    0000100: eeb7 005c 3a0b bb00 0259 1505 190a bb00
    0000110: 1459 b200 b419 0ac0 00b6 b600 c6b7 00c9
    0000120: 03b8 00df 3a13 3a12 0319 12b9 00e3 0100
    0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0000140: 1404 6015 1519 1215 14b9 00e6 0200 c000
    0000150: 053a 1819 1619 18b8 00f1 3a16 3615 3614
    0000160: a7ff d819 16b8 00ee b700 5c3a 0cb2 00f6
    0000170: b200 b405 bd00 0259 0319 0b53 5904 190c
    0000180: 53c0 00b6 b600 bab6 00f9 b02a b600 3303
    0000190: 32b6 00fb b0
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105]},{})
    append_frame(@151,Object[#125],Object[#125])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]})
    full_frame(@395,{Object[#2],Integer},{})

	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:179)
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:211)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:59)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:62)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:201)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:202)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
	at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:59)
	at scala.collection.generic.Growable$$Lambda$19/1787941794.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
	at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:48)
	at scala.sys.package$.env(package.scala:61)
	at scala.tools.nsc.settings.ScalaSettings.defaultClasspath(ScalaSettings.scala:30)
	at scala.tools.nsc.settings.ScalaSettings.defaultClasspath$(ScalaSettings.scala:30)
	at scala.tools.nsc.settings.MutableSettings.defaultClasspath(MutableSettings.scala:19)
	at scala.tools.nsc.settings.ScalaSettings.$init$(ScalaSettings.scala:57)
	at scala.tools.nsc.settings.MutableSettings.<init>(MutableSettings.scala:20)
	at scala.tools.nsc.Settings.<init>(Settings.scala:12)
	at scala.tools.nsc.Driver.process(Driver.scala:41)
	at scala.tools.nsc.Main.process(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.compiler.RawCompiler.apply(RawCompiler.scala:33)
	at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:159)
	at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:155)
	at sbt.IO$.withTemporaryDirectory(IO.scala:344)
	at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:155)
	at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:152)
	at sbt.IO$.withTemporaryDirectory(IO.scala:344)
	at sbt.compiler.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:152)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1.apply(ComponentCompiler.scala:121)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1.apply(ComponentCompiler.scala:118)
	at sbt.IO$.withTemporaryDirectory(IO.scala:344)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1$$anonfun$apply$2.apply$mcV$sp(ComponentCompiler.scala:118)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1$$anonfun$apply$2.apply(ComponentCompiler.scala:118)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1$$anonfun$apply$2.apply(ComponentCompiler.scala:118)
	at sbt.BufferedLogger.bufferQuietly(BufferedLogger.scala:31)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1.apply(ComponentCompiler.scala:116)
	at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1.apply(ComponentCompiler.scala:111)
	at sbt.IO$.withTemporaryDirectory(IO.scala:344)
	at sbt.compiler.IvyComponentCompiler.sbt$compiler$IvyComponentCompiler$$compileAndInstall(ComponentCompiler.scala:111)
	at sbt.compiler.IvyComponentCompiler$$anonfun$apply$1.apply$mcV$sp(ComponentCompiler.scala:102)
	at sbt.IfMissing$Define.apply(ComponentManager.scala:75)
	at sbt.ComponentManager.sbt$ComponentManager$$createAndCache$1(ComponentManager.scala:39)
	at sbt.ComponentManager$$anonfun$sbt$ComponentManager$$fromGlobal$1$1.apply(ComponentManager.scala:27)
	at sbt.ComponentManager$$anonfun$sbt$ComponentManager$$fromGlobal$1$1.apply(ComponentManager.scala:26)
	at sbt.ComponentManager$$anon$1.call(ComponentManager.scala:50)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.ComponentManager.lock(ComponentManager.scala:50)
	at sbt.ComponentManager.lockGlobalCache(ComponentManager.scala:49)
	at sbt.ComponentManager.sbt$ComponentManager$$fromGlobal$1(ComponentManager.scala:25)
	at sbt.ComponentManager$$anonfun$files$1$$anonfun$apply$2.apply(ComponentManager.scala:44)
	at sbt.ComponentManager$$anonfun$files$1$$anonfun$apply$2.apply(ComponentManager.scala:44)
	at sbt.ComponentManager.sbt$ComponentManager$$getOrElse$1(ComponentManager.scala:32)
	at sbt.ComponentManager$$anonfun$files$1.apply(ComponentManager.scala:44)
	at sbt.ComponentManager$$anonfun$files$1.apply(ComponentManager.scala:44)
	at sbt.ComponentManager$$anon$1.call(ComponentManager.scala:50)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.ComponentManager.lock(ComponentManager.scala:50)
	at sbt.ComponentManager.lockLocalCache(ComponentManager.scala:47)
	at sbt.ComponentManager.files(ComponentManager.scala:44)
	at sbt.ComponentManager.file(ComponentManager.scala:53)
	at sbt.compiler.IvyComponentCompiler.apply(ComponentCompiler.scala:102)
	at sbt.compiler.ComponentCompiler$$anon$2.apply(ComponentCompiler.scala:35)
	at sbt.compiler.AnalyzingCompiler.loader(AnalyzingCompiler.scala:118)
	at sbt.compiler.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:128)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:104)
	at sbt.compiler.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:62)
	at sbt.compiler.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:57)
	at sbt.compiler.CompilerCache$$anon$2.apply(CompilerCache.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:45)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:879)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:870)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:868)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
[error] (compile:compileIncremental) java.lang.reflect.InvocationTargetException
```

What's wrong?

**Comment by atapin** [comment]
Update to `java 1.8.0_112` has helped

**Comment by sjrd** [comment]
Probably a JVM bug, then. Shall we close this issue?
