### ISSUE TITLE
Could not find "phantomjs" on Win10 x64

### ISSUE THREAD

**Issue by brakmic** [scala-js/scalajs-tutorial#9]
Hi,

I get this error when trying to start the app:

```shell
D:\src\scala.js\scalajs-tutorial>sbt
[info] Loading global plugins from C:\Users\Harris\.sbt\0.13\plugins
[info] Loading project definition from D:\src\scala.js\scalajs-tutorial\project
[info] Set current project to Scala.js Tutorial (in build file:/D:/src/scala.js/scalajs-tutorial/)
> run
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.0, 2.11.5, 2.11.6) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Running tutorial.webapp.TutorialApp
java.io.IOException: Cannot run program "phantomjs": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:110)
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:140)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:479)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:539)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:533)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:110)
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:140)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:479)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:539)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:533)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) java.io.IOException: Cannot run program "phantomjs": CreateProcess error=2, The system cannot find the file specified
[error] Total time: 2 s, completed 07.11.2015 10:10:03
>
```

But I have nodejs + phantom installed. PhantomJS is a global package. Here's the result of my "where" command:
```shell
D:\src\scala.js\scalajs-tutorial>where phantomjs
C:\Users\Harris\AppData\Roaming\npm\phantomjs
C:\Users\Harris\AppData\Roaming\npm\phantomjs.cmd
```

NodeJS / npm versions I use:

```shell
D:\src\scala.js\scalajs-tutorial>npm -v  
2.11.3                                   
                                         
D:\src\scala.js\scalajs-tutorial>node -v 
v0.12.7                                  
```

**Comment by brakmic** [comment]
Here's the complete StackTrace:

```shell
> last compile:run                                                                                                                             
[info] Running tutorial.webapp.TutorialApp                                                                                                     
[debug] with JSEnv of type class org.scalajs.jsenv.phantomjs.PhantomJSEnv                                                                      
[debug] with classpath of type class org.scalajs.core.tools.classpath.LinkedClasspath                                                          
[debug] PhantomJS using webpage launcher at: C:\Users\Harris\AppData\Local\Temp\phantomjs-launcher-webpage7451180914749410914.html             
[debug] PhantomJS using launcher at: C:\Users\Harris\AppData\Local\Temp\phantomjs-launcher5341146008216701884.js                               
java.io.IOException: Cannot run program "phantomjs": CreateProcess error=2, The system cannot find the file specified                          
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)                                                                            
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:110)                                                  
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:140)                                                              
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:479)    
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:539)  
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:533)  
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)                                                                        
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)                                                                  
        at sbt.std.Transform$$anon$4.work(System.scala:63)                                                                                     
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)                                                             
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)                                                             
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)                                                                              
        at sbt.Execute.work(Execute.scala:235)                                                                                                 
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)                                                                              
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)                                                                              
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)                                               
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)                                                                      
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                            
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                             
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                            
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                     
        at java.lang.Thread.run(Thread.java:745)                                                                                               
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified                                               
        at java.lang.ProcessImpl.create(Native Method)                                                                                         
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)                                                                                  
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)                                                                                   
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)                                                                            
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:110)                                                  
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:140)                                                              
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:479)    
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:539)  
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:533)  
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)                                                                        
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)                                                                  
        at sbt.std.Transform$$anon$4.work(System.scala:63)                                                                                     
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)                                                             
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)                                                             
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)                                                                              
        at sbt.Execute.work(Execute.scala:235)                                                                                                 
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)                                                                              
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)                                                                              
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)                                               
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)                                                                      
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                            
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                             
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                            
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                     
        at java.lang.Thread.run(Thread.java:745)                                                                                               
[error] (compile:run) java.io.IOException: Cannot run program "phantomjs": CreateProcess error=2, The system cannot find the file specified    
```

**Comment by sjrd** [comment]
Make sure `phantomjs` is on your PATH. Can you run `phantomjs` from a commands line?

**Comment by brakmic** [comment]
Hi,

Yes, I can run phantomjs from the command line:
```shell
D:\src\scala.js\scalajs-tutorial>phantomjs
phantomjs>
```

**Comment by brakmic** [comment]
Well, it seems that under windows it isn't sufficient just to install phantomjs via npm. One has to download a zip-file from PhantomJS, unpack it somewhere and put it in PATH.

Well, because I'm not using PhantomJS in my development workflow I wasn't aware of these additional steps (download/unpack/set-path-manually).

Many thanks and maybe someone could put this info in the docs just to help some other (lost!) windows developer :)

Thanks :+1:
Harris
